nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_headers: ['X-Custom-Auth', 'Authorization', 'Accept', 'Content-Type']
        allow_methods: ['POST', 'PUT', 'GET', 'OPTIONS', 'DELETE']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['X-Custom-Auth', 'Authorization', 'Accept', 'Content-Type']
            allow_methods: ['POST', 'PUT', 'GET', 'OPTIONS', 'DELETE']
            max_age: 3600